// Generated by https://quicktype.io

export interface ReportData {
  reports: Report[];
}

export interface Report {
  source: string;
  date: string;
  notifiedall: number;
  notifiedsuspicious: number;
  notifieddiscarded: number;
  drawverticalline?: boolean;
  notifiedconfirmed?: number;
  confirmedisolation?: number;
  comments?: string;
  confirmedhospital?: number;
  confirmedcured?: number;
  highlightnotifiedall?: boolean;
  highlightnotifiedconfirmed?: boolean;
  confirmeddead?: number;
}
