// Generated by https://quicktype.io

export interface ReportData {
  reports: Report[];
}

export interface Report {
  source:             string;
  date:               string;
  notifiedall:        number;
  notifiedconfirmed:  number;
  notifiedsuspicious: number;
  notifieddiscarded:  number;
  confirmedisolation: number;
  confirmedhospital:  number;
  confirmedcured:     number;
  comments?:          string;
}
